ARGOeu/eosc-recommender-metrics

README.md
get_service_catalog.py
requirements.txt

A simple utility script to grab all available services in EOSC Marketplace catalog and produce a csv with the following information about each service:
`service_id, service_name, service_url`
Records are sorted by service_id
This correlation is performed in a single request
Example execution time and cli output:
```
time ./get_service_catalog.py
Retrieving page: marketplace list of services...
Grabbing url: https://marketplace.eosc-portal.eu/services?page=1&per_page=1000
Page retrieved!
Generating results...
File written to ./service_catalog.csv
./get_service_catalog.py  0.76s user 0.07s system 6% cpu 12.368 total
```
Example output csv format:
```
1,EGI Cloud Compute,/services/egi-cloud-compute
2,EGI High-Throughput Compute,/services/egi-high-throughput-compute
3,EGI Cloud Container …
```

Add utility script to get service catalog

---

get_service_catalog.py
preprocessor.py
rsmetrics.py

Incorporate `get_service_catalog.py` functionality in `preprocessor.py`

Incorporate get service catalog module to preprocessor

---

metrics.py
report.html.prototype
rsmetrics.py

Reorganise metrics.json output from a flat structure to lists of metrics and statistics like:
```json
{
"metrics": [
{
"name": "metric1",
"value": 18.9,
"doc": "explanation of metric"
}
],
"statistics": [
{
"name": "stat1",
"value": 33,
"doc": "explanation of statistic"
}
]
}
```

REC-55 Reorganize metrics output

---

get_service_catalog.py

REC-69 Fix get services parsing due to changes in marketplace page structure
Since new text is included in the parent item get service title from anchor item itself

REC-69 Fix get services parsing due to changes in marketplace page structure

---

preprocessor.py
rsmetrics.py

The new code:
- Supports a CSV format with two columns; the first column provides the service id while the second column provides the rating of the service.
- Rating is being retrieved from the Source (i.e. Mongo DB).
- The code, works for all config options of serving the services in services.csv.
If map_page is chosen (which is the default), it will try to find the rating in the Mongo DB. If not found, the service is withdrawn.

REC-24 Add the services rating info in the services.csv, as a second column in the CSV format file

---

preprocessor.py
rsmetrics.py

This PR resolves REC-75.
The previous format of the `services.csv` file was containing lines in the form of:
service_id, rating
In order to create additional metrics in RS Metrics such as top_5_services_recommended, more info must be passed in the services.csv file.
So, the current format is changed to:
`service_id, rating, service_name, service_page_id`
Note: The service_page_id should be retrieved from the page_map. If no page_id can be retrieved, then the service is removed from the process.

REC-75 Modifying services.csv file format to: service_id, rating, service_name,  service_page_id

---

preprocessor.py
rsmetrics.py

This PR resolves bug in dictionary creation according to REC-76.
In the Preprocessor, a dictionary under the name "dmap" is created, where the keys are the service ids and the values are the respective page ids, retrieved from the page_map file.
Some services (i.e. 433, 434) have commas inside their name, breaking the format of the dictionary and consequently the services.csv file output.
It should retrieve the page_id from the last entry of the page_map file in order to bypass the fact that a service name might include commas in its name.

REC-76 Bugfix in dictionary creation of service ids and pages id

---

metrics.py
preprocessor.py

This PR adds a new metric for the KPIs. The implementation calculates the Top 5 recommended services according to the recommendations entries.
It returns a list of lists with the elements:
1. service id
2. service name
3. service page appended with base (to create the URL)
4. the total number of recommendations for the service
5. the percentage of the (iv) to the total number of recommendations expressed in %, with or without anonymous, based on the function's flag
Service's info is being retrieved from the services.csv file (i.e. each line forms: service_id, rating, service_name, page_id)

REC-71 Top 5 services recommended metric is being added

---

metrics.py
preprocessor.py

This PR adds a new metric for the KPIs. The implementation calculates the Top 5 ordered services according to the recommendations entries.
User actions with Target Pages that lead to unknown services (=-1) are being ignored.
It returns a list of lists with the elements:
1. service id
2. service name
3. service page appended with base (to create the URL)
4. the total number of orders of the service
5. the percentage of the (iv) to the total number of orders expressed in %, with or without anonymous, based on the function's flag
Service's info is being retrieved from the services.csv file (i.e. each line forms: service_id, rating, service_name, page_id)

REC-72 Top 5 services ordered metric is being added

---

metric_descriptions/catalog-coverage.yml
metric_descriptions/click-through-rate.yml
metric_descriptions/diversity-gini.yml
metric_descriptions/diversity.yml
metric_descriptions/hit-rate.yml
metric_descriptions/novelty.yml
metric_descriptions/user-coverage.yml
webservice/app.py
webservice/templates/kpis.html
webservice/templates/metric_desc.html
webservice/templates/report.html.prototype
webservice/templates/rsmetrics.html

Add main rs metric dashboard to web ui

REC-86 Add metric dashboard main page to the ui

---

webservice/templates/kpis.html
webservice/templates/metric_desc.html
webservice/templates/rsmetrics.html

This PR creates an alphabetical order of the metrics' descriptions in the UI's sidebar.

Sorting the metrics description fields in sidebar

---

metrics.py
webservice/templates/kpis.html
webservice/templates/metric_desc.html
webservice/templates/rsmetrics.html

A new implementation of the Diversity Gini Index is presented here. It is based on the initial formula covered in https://link.springer.com/10.1007/978-1-4939-7131-2_110158 and includes in the computation the services of 0 occurrence in recommendations.
More info in REC-93.

REC 93, Part c: New implementation of the Gini Index (basic) including services of 0 occurrence

---

metrics.py
preprocessor.py
rsmetrics.py

REC-95 Retrieve service name from EOSC-Marketplace

---

metric_descriptions/novelty.yml
metrics.py
webservice/templates/metric_desc.html

- Calculate novelty using mean self-information (MSI) user as a simpler expression
- Gather user actions of registered users and identify and keep the ones that refer to transitions that land on service description pages
- Calculate the views of each service based on that
- Calculate for each recommended service its p(i) (based on views) and its -log(p(i))
- Sum and divide by |R| to get the novelty metric

REC-97 Calculate novelty using simpler expression

---

preprocessor.py
rsmetrics.py

By this PR:
- The  RS Metrics reads all data (users, resources, user_actions and recommendations) from the Datastore (RS Metrics Mongo DB)
- The recommendation actions are broken into recommendation items
- Fix collection field types in Preprocessor when storing data (e.g. the service id in Service collection is Integer instead of String)
- An identical mechanism for reading the configuration file that exists in the Preprocessor has been established in the RSMetrics too. Currently, the same configuration file is used among both modules.

REC-126 Read data from RS Metrics MongoDB Datastore

---

metrics.py
preprocessor.py
rsmetrics.py

This PR solves REC-104, REC-122 and REC-123.
Specifically,
- It establishes the functionality to store metrics and statistics in the RS Metrics MongoDB Datastore
- It defines a new schema for the metrics collection where it contains all elements that already exist in the metrics.json file, whereas it adds the type of resource that these metrics are concerned about (e.g. service) and the provider of the resources
- It defines a basic ingestion policy

REC-104 Store in RS Metrics MongoDB (Datastore)

---

config.yaml
metrics.py
preprocessor.py
rsmetrics.py

This PR resolves REC-124 and REC-125. That is:
- Removal of the unneeded CSV and JSON file exporting functionality from Preprocessor
- Removal of the unneeded JSON file exporting functionality from RS Metrics
- Removal of the respective option from the configuration file format
- Removal of the `input` flag from RS Metrics since no files or directory is needed
The `output` flag that specifies the output directory at the Preprocessor is preserved since page_map might be set as a source option, thus a directory would be needed to be assigned.

REC-124 Removal of the unneeded CSV and JSON file export from both Preprocessor and RS Metrics

---

webservice/app.py
webservice/templates/kpis.html
webservice/templates/metric_desc.html
webservice/templates/rsmetrics.html

REC-130 Update UI to support reports
Preprocessor & evaluation components now support producing results per provider (as different reports). API and UI must be extended to support results from different providers in the form of reports
Change endpoint paths to incorporate the notion of `report`. Each report is named after the provider. The API paths change in the following order:
👉 **get metrics** 
from: `/api/metrics`
to: `/api/reports/{provider-name}/metrics`
👉 **get statistics**
from: `/api/statistics`
to: `/api/reports/{provider-name}/statistics`
👉 **get all (both metrics & statistics)**
from: `/api`
to: `/api/reports/{provider-name}`
similar changes in subpaths (for example for selecting _specific_ **metric** or **statistic**)
There is also a new api method `get_available_reports` …

REC-129 Update api to support reports

---

README.md
config.yaml
preprocessor_common.py

In this PR, the affected software is the `preprocessor_common.py`:

REC-134 Remove intermediate files and add caching option

---

metrics.py

A new metric has been added providing a statistical report on the recommendations per day. Specifically, it produces a dictionary for each particular day found with its respective number of recommendations committed. The dictionary includes all in-between days (obviously, with the count set to zero).

REC-113 Recommendations per day metric has been added

---

metrics.py

A new metric has been added providing a statistical report on the user_actions per day. Specifically, it produces a dictionary for each particular day found with its respective number of user_actions committed. The dictionary includes all in-between days (obviously, with the count set to zero).

REC-114 User actions per day metric has been added

---

metrics.py
preprocessor.py
webservice/app.py
webservice/templates/graphs.html
webservice/templates/kpis.html
webservice/templates/rsmetrics.html

Create a new dashboard view to display graphs for `user actions per day` and `recommended items per day` statistics

REC-150 create a new view to display graphs

---

metrics.py

The current implementation returns a list of values based on the indexes found in each collection separately.
With this fix, the resulting period is the same for both collections and equal to end_time - start_time (retrieved for the respective statistics).
See ticket REC-152.

REC-152 user_actions and recommendations per day statistics return same period

---

environment.yml
requirements.txt

This PR adds a newer version of certifi suggested by the dependabot, after checking that it does not break anything.

Manual Bump certifi from 2021.10.8 to 2022.12.7

---

rs-stream.py

Ingest data in streaming mode from rs-queues
Develop a simple cli client `rs-stream.py` to be able to connect to the rs queues and ingest data. This first example uses the stomp python library to connect to an activemq system and ingest specific user_action data that are stored in a mongo datastore
example usage:
```
./rs-stream.py -a username:password -q host:port -t user_actions -d ""mongodb://localhost:27017/datastore"" -p provider_name
```

REC-160 Create a stream connector to ingest msgs from rs queue

---

webservice/.env
webservice/app.py

⚠️ please merge first: https://github.com/ARGOeu/argo-ansible/pull/542 
Update current health check endpoint `/diag` to display status information about the datastore component, the api and the streaming connectors. General status of the service is affected by api and datastore. Streaming status can be down or paused momentarily without the service being affected. __todo: We can extend the checks to affect general status if streaming is down for a long period of time__
Example response (with streaming temporarily down):
```json
"RS_metrics": {
"status": "UP",
"RS_metrics_api": {
"status": "UP"
},
"RS_metrics_datastore": {
"status": "UP"
},
"RS_streaming": {
"status": "DOWN",
"RS_streaming_user_actions": {
"status": "DOWN"
},
"RS_streaming_mp_events": "DOWN"
}
}
```

REC-199 Update healthcheck with db and streaming statuses

---

rs-stream.py
rsmetrics.py

This PR handles service events. Particularly:
- It modifies the `resources` collection so that:
- if an `update` or `delete` keyword is found in `cud`, then it updates the user entry, concerning the fields: name, deleted_on, type, provider, and ingestion. In the `delete` case the `deleted_on` entry is set with the timestamp of the event, otherwise, it is set to None.
- if a `create` keyword is found in `cud`, then it creates a new user. The fields that are set are: name, created_on, deleted_on, type, provider, and ingestion. The `created_on` entry is set with the timestamp of the event.
- Additionally, the `rsmetrics.py` was modified so that it filters users based on their `created_on` or `deleted_on` values.
- Specifically, if a resource has the `created_on` or the `deleted_on` value set …

REC-175 Process service_events and update service information accordingly

---

environment.yml
preprocessor.py
preprocessor_common.py
requirements.txt
rsmetrics.py

This PR solved REC-204, where it moves the handling concerning the user_actions from the preprocessor to preprocessor_common.
Meanwhile, the following fixes have been made:

REC-204 Move user actions from preprocessor to preprocessor_common

---

config.yaml
preprocessor_common.py
rs-stream.py

REC-211 Collect categories and scientific domains

---

metrics.py

A monthly statistic has been added in a similar way to the daily statistics for both user actions and recommendations.
It returns a dictionary of entries in the format of:
```
{
"date": "YYYY-MM",
"value": count
}
```

REC-212 New statistics: Monthly user actions and recommendations

---

metrics.py
rsmetrics.py

About the new KPI metric:
- Two inner joins are performed. The first one is for connecting recommendations with the category ids and the second join in order to retrieve and associate the category name to the respective ids. Since it is an inner join, if no association is found, entries are dropped.
- The total number of recommendations takes into account those recommendations that have services with a known category.

REC-214 RS Metrics: Top 5 categories for recommendations

---

metrics.py
rsmetrics.py

About the new KPI metric:
- Two inner joins are performed. The first one is for connecting recommendations with the scientific domain ids and the second join in order to retrieve and associate the scientific domain name to the respective ids. Since it is an inner join, if no association is found, entries are dropped. 
- The total number of recommendations takes into account those recommendations that have services with a known scientific domain.

REC-215 RS Metrics: Top 5 scientific domains for recommendations

---

metrics.py
rsmetrics.py

About the new KPI metric:
- Two inner joins are performed. The first one is for connecting orders with the category ids and the second join in order to retrieve and associate the category name to the respective ids. Since it is an inner join, if no association is found, entries are dropped.
- The total number of orders takes into account those orders that have services with a known category.

REC-216 RS Metrics: Top 5 categories for orders

---

metrics.py
rsmetrics.py

About the new KPI metric:
- Two inner joins are performed. The first one is for connecting orders with the scientific domain ids and the second join in order to retrieve and associate the scientific domain name to the respective ids. Since it is an inner join, if no association is found, entries are dropped. 
- The total number of orders takes into account those orders that have services with a known scientific domain.

REC-217 RS Metrics: Top 5 scientific domains for orders

---

metrics.py
preprocessor.py
preprocessor_common.py
rs-stream.py
rsmetrics.py

- URL paths and click transactions are exactly the same as before (including the rewarding mechanism)
- **EXCEPT FOR**:
- when a user clicks from the search page to a service landing page
- when a user clicks a recommendation from the search page to a service landing page 
- there is NO USER ACTION when clicking from a service landing page back to the search menu
- Therefore when catching `search%2F...` regular expression in the source page, then it is swapped with /services.
In the `current` schema, user actions are filled with a `resource_id` attribute. Therefore we use this id to a reverse lookup table in order to find the correct page.
- Preprocessing is backward compatible for the new exceptions (so reward and URL paths are always fixed)
Important: In order to calculate the reward, …

REC-225 Fix URL paths and re-add reward mechanism

---

rsmetrics.py
webservice/app.py

Added support for both legacy and current reports in ui in the simplest way possible

REC-240 Support legacy and current reports in ui

---

README.md
get_catalog.py

Make get_catalog script to be able to store the items that grabs from marketplace to a datastore (mongodb)

REC-251 Make catalog script to be able to store results in mongodb

---

metrics.py
rsmetrics.py
webservice/app.py
webservice/templates/kpis.html
webservice/templates/rsmetrics.html

Since we are creating evaluations for different types of items (and not just "services") change hardcoded references to `services` to be more generic and replace them with `items`

REC-252 Wherever referenced: change services to items

---

webservice/templates/rsmetrics.html

Reference `items` statistic in data as `data['items']` to avoid jinja/python confict with items dictionary method

REC-256 Fix statistic:items reference in jinja template

---

config.yaml
metrics.py
rs-stream.py
rsmetrics.py

REC-248 Support evaluation of training material

---

metric_descriptions/click-through-rate.yml
metric_descriptions/hit-rate.yml
metrics.py
preprocessor_common.py
rsmetrics.py
webservice/app.py
webservice/templates/rsmetrics.html

This PR introduces:
1.  New statistics for registered and anonymous users. 
2. The metrics calculations, the KPIs and the graphs now support both registered and anonymous users.
In detail:
* The internal field of aai_uid of the Pandas dataframe of both the user actions and the recommendations now keeps the aai_uid value of the registered users or the unique_id value of the anonymous users. Additionally, an extra column of user actions and recommendations determining registered or anonymous users (True/False) has been added to the Pandas dataframe of both the user actions and the recommendations.
* Items are now read in string format.
* Users are being created from the user actions for both registered and anonymous users.
* The statistics "registered_users", "anonymous_users", "item_views" …

REC-258 Support metrics calculations for anonymous users

---

metric_descriptions/hit-rate.yml
metrics.py
rsmetrics.py
webservice/templates/kpis.html
webservice/templates/rsmetrics.html

This PR:
- Adds backward compatibility to legacy mode. Metrics are now calculated with registered and anonymous users on new UI format. Again, same logic as in current mode. Set 0 to the internal Dataframe field user_id when anonymous, otherwise the value of user_id as it is MongoDB (for registered users).
- Top5 KPIs now always return a list (even empty), so UI does not break.
- Minor changes in icon and color of Hit Rate, because the same was used for the new statistic Item Views, before.
- Minor typo with missing % for anonymous percentage in UI

REC-262 Add support for legacy mode and preserve list as an output of top5 KPIs

---

rsmetrics.py

It seems that pymongoarrow returns pandas dataframe with convert_dtypes=True, therefore None values are treated as np.nan;

REC-277 convert np.nan to None types

---

metrics.py
rsmetrics.py
webservice/app.py
webservice/templates/kpis.html

This PR:
- swap Top5 ordered results to Top5 viewed, where Top5 KPIs indicate results for both registered and anonymous users now
- fix class type (i.e. string) issue in item views statistic and novelty metric
- swap `find_pandas_all` to `find` regular function call, cause of a bug in reading different class types (i.e. string, integers) simultaneously from MongoDB

REC-264 Convert top5 ordered to top5 viewed, fix in item views and novelty

---

README.md
get_catalog.py
rsmetrics.py

Concerning the `get_catalog.py`:
1. A `timestamp` field is added that takes a date-time value generated at the UTC time the script ran.
2. By default, the get_catalog does not remove old entries at the resources collection.
Concerning the `rsmetrics.py`:
1. A new argument is added under the name `tag`.
2. Results are now stored with the `name` of the given `tag` (and the old ones deleted).
3. All the latest unique resources/items at the date-time range of the given start/end time are retrieved for further processing.
A typical `rsmetrics.py` command for a monthly report, would be:
```bash
./rsmetrics.py -p provider -s $(date +"%Y-%m-01") -e $(date +"%Y-%m-%d") -t "$(date +"%B %Y")"
```

REC-263 Add timestamp to resources and add tag in metrics

---

README.md
monitor.py

The monitor firstly checks if the connection is established and then fetches the number of documents found in `user_actions`, `recommendations`, and `resources`.  Then for each one of them finds the distinct `types` and then for each `type` it counts the documents found.
A typical example for looking at 1 day ago would be:
```bash
./monitor.py -d "mongodb://localhost:27017/rsmetrics" -s "$(date -u -d '1 day ago' '+%Y-%m-%d')" -e "$(date -u '+%Y-%m-%d')"
```

REC-286 Monitor for entries in Datastore

---

README.md
monitor.py

New feature:
E-mail send over SMTP for the above example:
```bash
./monitor.py -d "mongodb://localhost:27017/rsmetrics" -s "$(date -u -d '1 day ago' '+%Y-%m-%d')" -e "$(date -u '+%Y-%m-%d')" --email "smtp://server:port" sender@domain recipient1@domain recipient2@domain
```

REC-292 Add e-mail support for the RS Monitor

---

rsmetrics.py

For large dataset we use `--use-cache` parameter which does not retrieve resources on-the-fly from the EOSC Marketplace. Instead it uses the resources found in MongoDB.
The problem is that the rsmetrics calculations checks if the resources are within the given datetime range for computations. However, since those large datasets are retrieved on best-effort their timestamp might not be within that particular datetime range.
Therefore, as a solution, a new parameter is introduced `--ignore-timestamp` in order to ignore that timestamp check.
Usage Example:
```Bash
./rsmetrics.py -p online_engine -s $(date +"%Y-%m-01") -e $(date +"%Y-%m-%d") -t "$(date +"%B %Y")" --use-cache --ignore-timestamp
```

REC-297 Add support to ignore timestamp when necessary

---

config.yaml
rs-stream.py

This PR adds the ability to listen to recommendations provided by the Content-based Engine (Athena).

REC-289 Add Athena support in rs-stream.py
