README.md, report.html.prototype, report.py
Generate html report based on evaluation result files (metrics.json and pre_metrics.json)
Implemented an html page prototype which automatically tries to retrieve from the same relevant path the file metrics.json (will optionally take into account pre_metrics.json also later). The page embeds all necessary javascript and uses Bootstrap and FontAwesome css libs with external references. 
A python script `report.py` takes as argument an input folder (with the evaluation metrics) and an output folder (where the report will be generated and served). It creates the output folder (if it doesn't exist) and transfers all the necessary files (html and json). Then spawns automatically a python local webserver. The webserver serves the specific output directory with the report being the index.html …
=> Initial report generation and implementation

preprocessor.py
File dataset.csv was empty after #6 integration. Now, it is fixed
=> fix in searching pageid in dict

pre_metrics.py, preprocessor.py
Commit includes:
- Pre-metrics have been encapsulated in functions and appended with description (see REC-24)
- Bug-Fix in user_coverage calculation
- Services' selection in configuration is set to publish by default
=> [REC-24] Pre-metrics have been encapsulated in functions and appended with description

metrics.py, preprocessor.py, report.html.prototype, rsmetrics.py
Implement calculation of hit rate which is the number of users with at least one hit / total users. A user that has at least one service being recommended to him and also accessed by him is considered a hit
The rs db dump includes information per user for his accessed services. The users.csv file is enriched with this info in a second column containing a space separated list of service id's considered accessed by the user
=> [REC-46] Calculate hit-rate

metrics.py, report.html.prototype, rsmetrics.py
CTR = num_of_clicks_on_recommendation_panel_items / num_of_times_recommendation_panel_items_displayed
* Important note: In some cases such as this it is useful to have the full user action list unfiltered thus removed the pre-filtering of user actions by service & user (this can be done on the metrics that is actually required)
=> REC-50 Add Click-Through Rate Metric

metrics.py
The first version of the Shannon Entropy metrics. 
Computation is based on the https://elliot.readthedocs.io/en/latest/_modules/elliot/evaluation/metrics/diversity/shannon_entropy/shannon_entropy.html#ShannonEntropy source code and the respective reference at https://link.springer.com/content/pdf/10.1007/978-1-4899-7637-6.pdf, page 293.
The entropy is 0 when a single item is always chosen or recommended, and log n when n items are chosen or recommended equally often.
More info at REC-49.
=> [REC-49] First version of Shannon Entropy metric computation

metrics.py, report.html.prototype
=> REC-52 Add diversity metric to report

metrics.py
First version of the Novelty based on https://elliot.readthedocs.io/en/latest/_modules/elliot/evaluation/metrics/novelty/EFD/efd.html#EFD. See REC-53
=> REC-53 First version of novelty

report.html.prototype
=> REC-57 Add novelty to the UI

metrics.py
This PR adds the Diversity Gini Index according to [https://elliot.readthedocs.io/en/latest/_modules/elliot/evaluation/metrics/diversity/gini_index/gini_index.html#GiniIndex](https://elliot.readthedocs.io/en/latest/_modules/elliot/evaluation/metrics/diversity/gini_index/gini_index.html#GiniIndex). See REC-58
=> REC 58 Adding the GiniIndex Diversity

metrics.py, report.html.prototype, rsmetrics.py, webservice/app.py
Allow api to return information about specific metrics and statistics
=> REC-63 Serve individual statistics and metrics from webservice api

rsmetrics.py
REC-42 Making services.csv mandatory by removing services flag. Resolving ticket.
=> REC-42 Making services.csv mandatory by removing services flag

metrics.py, rsmetrics.py
REC-64 Removing backup plan for calculating users and services, since users.csv and services.csv files are mandatory. Resolving ticket.
=> REC-64 Removing backup plan for calculating users and services, since csv files are mandatory

metric_descriptions/catalog-coverage.yml, metric_descriptions/diversity-gini.yml
The first version of the metric description has been added. See REC-78.
=> REC-78 First version of Catalog Coverage YAML file

metric_descriptions/diversity-gini.yml
The first version of the metric description has been added. See REC-77.
=> REC-77 First version of Diversity Gini Index YAML file

metric_descriptions/diversity-gini.yml
Fixing typos at the initial REC-77 (PR-39)
=> REC-77 b Fixing typos at the initial REC-77 (PR-39)

metric_descriptions/click-through-rate.yml
The first version of the metric description has been added. See REC-79.
=> REC-79 First version of Click-Through-Rate YAML file

metric_descriptions/hit-rate.yml
The first version of the metric description has been added. See REC-80.
=> REC-80 First version of Hit Rate YAML file

metric_descriptions/user-coverage.yml
The first version of the metric description has been added. See REC-83.
=> REC-83 First version of User Coverage YAML file

pre_metrics.py
=> REC-41 Preprocessor: Renaming recommendations to recommendation_actions

metric_descriptions/catalog-coverage.yml, metric_descriptions/user-coverage.yml, webservice/templates/metric_desc.html, webservice/templates/rsmetrics.html
Add links to metric description pages for each metric displayed in the front rsmetrics page
Remove links from headings describing steps in the process section of metric description page
=> REC-89 Add url to the metric page

webservice/app.py, webservice/templates/kpis.html, webservice/templates/rsmetrics.html
- Add data range information (start/end datetimes) on ui
- Add report generated on datetime info
=> REC-28 Add date range info on ui

metrics.py
This PR integrates a new implementation of the Shannon Entropy which is based on the classic mathematical expression. 
It is inspired by the code: https://github.com/flaviodipalo/RecSys-Project/blob/48036c5d3870eacd906477df8430ae0ea4bf41ce/Matrix_Factorization_optimization/Base/Evaluation/metrics.py#L162
=> REC49 - New implementation of the Shannon Entropy (Elliot diversity is being removed)

metric_descriptions/diversity.yml
This PR updates the ticket REC49.
Part b: Update of the YAML file describing the new implementation of the Shannon Entropy.
=> REC49 - Part b: Update of the YAML file describing the new implementation of the Shannon Entropy

webservice/templates/rsmetrics.html
Fix in dashbaord/rsmetrics jinja template the value of diversity to be dynamic
=> Template fix diversity dynamic value

webservice/app.py
Remove redundant close statements
=> Remove redundant close statements

metric_descriptions/diversity-gini.yml
This PR updates the YAML file for Diversity Gini Index, according to the 0-occurrence algorithm. More info in REC93.
=> Rec-93 Part d:  YAML file update for Diversity Gini Index, according to the 0-occurrence algorithm

config.yaml, pre_metrics.py, preprocessor.py
This PR append the pre_metrics collection with two fields:
- the **type** of the resource, e.g. service
- the **provider** of the resource, e.g. grnet
=> REC-120 Pre-metrics new definition schema in Datastore

environment.yml, requirements.txt, webservice/.env, webservice/app.py
=> REC-101 Update webservice app to use mongodb as datastore

JenkinsFile
=> REC-136 Add a boilerplate jenkinsfile

environment.yml, preprocessor.py, preprocessor_common.py, requirements.txt, rsmetrics.py
=> REC-135 Optimise mongo data ingestion to panda dataframes

webservice/templates/graphs.html, webservice/templates/kpis.html, webservice/templates/metric_desc.html, webservice/templates/rsmetrics.html, website/docs/policies/Terms.md, website/docs/policies/_category_.json, website/docs/policies/tom.md, website/package-lock.json
- Add terms of use page in docs
- Add tom page in docs
- Add relevant links to footer of each ui page
=> REC-153 Add policy/terms pages and relevant links to ui

metric_descriptions/accuracy.yml, metrics.py, website/docs/metrics_descriptions/accuracy.md, website/docs/metrics_descriptions/catalog_coverage.md, website/docs/metrics_descriptions/click_through_rate.md, website/docs/metrics_descriptions/diversity_shannon_entropy.md, website/docs/metrics_descriptions/hit_rate.md, website/docs/metrics_descriptions/novelty.md, website/docs/metrics_descriptions/user_coverage.md, website/docs/policies/privacy.md
This PR introduces the first version of the accuracy metric. 
- It calculates the accuracy of the recommendations based on the registered users' visits. 
- A mean value is returned. 
- It is considered an accuracy value of 1 when a user is not recommended at all and has not visited any service.
=> REC-110 First version of the accuracy metric with documentation

metric_descriptions/accuracy.yml, webservice/app.py, webservice/templates/rsmetrics.html
This PR adds the Accuracy metric to the RSMetrics webpage UI.
=> REC-165 Add Accuracy in RSMetrics UI

Jenkinsfile, environment.yml, get_service_catalog.py, metrics.py, preprocessor.py, preprocessor_common.py, report.py, requirements.txt, retrieval.py, reward_mapping.py, rs-stream.py, rsmetrics.py, webservice/app.py
Apply style fixes in python files
=> REC-180 Enable python syntax style checks using flake8

rs-stream.py
- Group connect and subscribe functionality in one function
- Use on_disconnect method on Listener to call connect & subscribe
- Add connection check in loop
=> REC-188 stream connector reconnect on disconnect

README.md, rs-stream.py
This PR handles the user events that the Listener retrieves. 
- In this version, every entry is saved in the user_events_streaming collection.
- It saves according to model type:
- if the model is User it saves the entry to user events collection
- if the model is Service it saves the entry to service events collection
- else, it saves it to other events collection
- Minor add about the user actions; every entry is saved in the user_actions_streaming collection.
- README file is updated with info about the Streaming System
=> REC-163 First version of the User events extraction and storing

rsmetrics.py
The final target is to use Cyfronet's user actions. Currently, this is done with a static assignment.
=> REC-191 Statically usage of the Cyfronet user actions

webservice/templates/rsmetrics.html
Remove irrelevant metric item: orders by unregistered users
=> Remove orders unregistered metric

rs-stream.py, rsmetrics.py
This PR handles user events. Particularly:
- It modifies the `users` collection so that:
- if an `update` or `delete` keyword is found in `cud`, then it updates the user entry, concerning the fields: accessed_resources, deleted_on, provider, and ingestion. In the `delete` case the `deleted_on` entry is set with the timestamp of the event, otherwise, it is set to None.
- if a `create` keyword is found in `cud`, then it creates a new user. The fields that are set are: accessed_resources, created_on, deleted_on, provider, and ingestion. The `created_on` entry is set with the timestamp of the event.
- Additionally, the `rsmetrics.py` was modified so that it filters users based on their `created_on` or `deleted_on` values.
- Specifically, if a user has the `created_on` or the `deleted_on` …
=> REC-174 Process user_events and update user information accordingly

metrics.py, rsmetrics.py
Filter by date in db query instead of doing it later in dataframes
=> REC-208 Use same field names in db and in python dataframes

rsmetrics.py
Log error and skip computations when
- no user action data 
- no recommendation data 
- no user data
- no resource data
=> REC-209 Skip computations when no data found

environment.yml, requirements.txt, website/package-lock.json, website/package.json
Update api dependencies
Update docusaurus dependencies
Based on:
https://github.com/ARGOeu/eosc-recommender-metrics/pull/102
https://github.com/ARGOeu/eosc-recommender-metrics/pull/120
https://github.com/ARGOeu/eosc-recommender-metrics/pull/124
https://github.com/ARGOeu/eosc-recommender-metrics/pull/126
https://github.com/ARGOeu/eosc-recommender-metrics/pull/131
=> Update api and docusaurus dependencies

webservice/templates/graphs.html
Add monthly user_actions and recommendations to the ui
=> REC-203 Add monthly user_actions and recommendations to the ui

webservice/templates/kpis.html
- Add top 5 recommended categories
- Add top 5 ordered categories
- Add top 5 recommended service domains
- Add top 5 recommended services
=> REC-203 Add category & domain related kpis to the ui

rs-stream.py, rsmetrics.py
- It stores the recommendation to the RS Metrics datastore accordingly.
- It stores all recommendations found.
- Currently, it supports recommendations that come from the Cyfronet provider only.
=> REC-132 First draft of the recommendations stream handler

webservice/app.py
=> REC-240 Fix graph route typo

preprocessor.py, preprocessor_common.py, rs-stream.py
If an aai_uid variable arrives of string type with no characters in the string (i.e. ""), convert it to None, so that further processing works properly.
=> Convert a aai_uid empty string to null

webservice/app.py
Return report names sorted by the most recent one
=> REC-243 Api get report names sorted by the most recent one

webservice/templates/graphs.html, webservice/templates/kpis.html, webservice/templates/metric_desc.html, webservice/templates/rsmetrics.html
Allow in UI selection box, reports to be sorted by most recent
=> REC-244 Ui selection box allow reports to be sorted by most recent

rs-stream.py
* User actions and recommendations are now able to store data independetly of the data type (e.g. service, training etc.)
* Resource_lookup has been removed, whereas JMS message's attribute is used instead, in order to assocate page_id and resource_id. Association is agnostic to data type also.
Conflict:
* The **click_through_rate** metric must be redefined. Additionally, the metric should support both legacy and current data format.
=> REC-253 Prepare user actions and recommendations to accept any known type

README.md, config.yaml, metrics.py, preprocessor_common.py, rsmetrics.py
Update provider names to use the recommendation engine names
=> REC-246 Update provider names with rec engine ones

metrics.py
- The URL of the Top5 items with this bug fix currently supports all items redirections.
- Additionally, a bug fix made for the statistic items_views_registered which should have followed the same logic as in items_views, which now does.
=> REC-265 Fix Top5 items urls and statistic items_views_registered

config.yaml, metrics.py
Fix the missing / in https, cause it was leading to the landing page instead of the link.
Add Athena RS in config file.
=> Fix missing slash in https and add missing value in config

metrics.py, rsmetrics.py
In this PR:
- Introduce an "errors" field in metrics collection that stores the function names of those that produced an error/exception. If no errors then return an empty list.
- Every metric (scalars or lists) in case of error is now returning None.
- Implementation Note: When using the pass_on_error decorator, the function that decorates must contain a Runtime Class Object.
=> REC-269 Store errors with function names in report

get_catalog.py, rsmetrics.py
- get_catalog now accepts only one provider per resource request
- makes provider required field in order to avoid future mistakes
=> REC-266 Keep one provider per resource item

webservice/.env, webservice/app.py
Update rseval api healtcheck endpoint to include status for recommendations stream job
=> REC-279 Update healthcheck to include recommendations stream check

environment.yml, requirements.txt
Based on : https://github.com/ARGOeu/eosc-recommender-metrics/pull/191
The code seems to work fine under the new update.
=> Update urllib version based on alert

rs-stream.py
- The collection of users is generated based on the unique users found in the user actions, including registered and anonymous users.
=> REC-242 Users are not longer retrieved. Users are generated based on user actions

get_catalog.py
Bugfix in get_catalog concerning services and data_sources capturing
=> REC-290 Bugfix in get_catalog concerning services and data_sources capturing

metrics.py, rsmetrics.py
With this patch, the filtering is performed according to provider AND resource type determination (as defined in the configuration file). Previously, all provider's items were fetched.
=> REC-299 filter resource types according to configuration

requirements.txt, website/package-lock.json
- Add missing dependencies in `requirements.txt`
- Update versions of several libraries in the `website` dir
=> Updating versions

website/docusaurus.config.js
Add cc info in documentation header
=> AO-910 Add documentation cc info
